### ISSUE TITLE
Song fails to play and loops loading sound

### ISSUE THREAD

**Issue by weruder** [picoriley/Turntable#103]
Repro steps:
1. Load a track by dragging into the window
2. Use the stop command to stop the song
3. Load the same track by dragging into the window
4. Stop the track again with the stop command
5. Drag a different track into the window

Metadata doesn't display and the record spins while playing the loading sound effect. Closing the player gives the message "Failed to release a song".

**Comment by picoriley** [comment]
No longer repro's, probably fixed by #106
